# 임시 디렉터리 경로
temp_directory: '/var/tmp'

# 백업 장치
backup_storage:
  - type: smb
    host: your-nas-hostname
    share_path: 'share/backup'
    user: nas-username
    password_env: DOMI_NAS_PASSWORD

# SQL 백업 설정
sql:
  host: 127.0.0.1
  port: 3306
  user: root
  password_env: DOMI_SQL_PASSWORD
  databases:
    - mydb1
    - mydb2

# 백업 폴더
backup_targets:
  - name: my-project
    source_paths:
      - ['target', '/home/user/projects/my-project']

  - name: documents
    source_paths:
      - ['', '/home/user/Documents']

# Prometheus 설정
prometheus:
  enable: true
  path: './prometheus.prom'
